feat: add cloud-init deployment
WhatsApp/proxy pull request #88
Opened 2023-01-09 05:28 UTC by matinzd

Add cloud-init deployment

2023-01-10 03:39 UTC, gmale commented on cloud/cloud-init.yml
> +  - docker compose -f $HOME/whatsapp-proxy/proxy/ops/docker-compose.yml up -d
nit: newline missing

2023-01-10 13:00 UTC, matinzd commented on cloud/cloud-init.yml
> +  - docker compose -f $HOME/whatsapp-proxy/proxy/ops/docker-compose.yml up -d
Fixed.

2023-01-10 17:13 UTC, matinzd commented
@gmale @slawlor

2023-01-12 21:41 UTC, slawlor requested changes
Please separate the cloud init bits to another readme in a `doc/` folder. Then just list a pointer to it in the readme. We're going to add more common deployments in the future, and I don't want the main page cluttered for the bulk of our users.

Thanks

2023-01-12 21:53 UTC, matinzd commented
> Please separate the cloud init bits to another readme in a `doc/` folder. Then just list a pointer to it in the readme. We're going to add more common deployments in the future, and I don't want the main page cluttered for the bulk of our users.
> 
> Thanks

Done!

2023-01-13 00:04 UTC, slawlor approved these changes
Thank you for contributing!

2023-01-13 00:05 UTC, merged

2024-11-30 22:36 UTC, Sultan12490 commented on cloud/cloud-init.yml
> +  - docker compose -f $HOME/whatsapp-proxy/proxy/ops/docker-compose.yml up -d
Hl